### ISSUE TITLE
Interesting thread-related errors after linking to the HDF5 static libraries

### ISSUE THREAD

**Issue by LTLA** [usnistgov/libhdf5-wasm#1]
You may be interested in the curious case of https://github.com/LTLA/h5wasm-pthreads-MRE.

In short, I was attempting to link to the HDF5 libraries while also enabling Pthreads support using the latest Emscripten (3.1.9). I wasn't using HDF5 in any parallel sections - or anywhere at all, actually, for that MRE. Regardless, the mere existence of HDF5 code in the Wasm binary was sufficient to cause segmentation faults in the multi-threaded code. 

I speculate that HDF5 is running something when the library is first loaded in each thread (I believe this loading occurs on first use of the thread). I would then guess that, whatever HDF5 is doing, it's not thread-safe, and it breaks something in shared memory if two or more threads are doing it at exactly the same time. This causes segmentation faults in SAFE_HEAP mode.

Compiling HDF5 with the thread-safe flag enabled doesn't seem to help, even after I adjust the MRE code to only use the base C API. If I had to guess, the thread safety only covers API calls after the library's globals are initialized. However, for web workers, the globals would need to be initialized for each thread, which could then cause race conditions on the SharedArrayBuffer. 

This issue only occurs on the latest version of Emscripten. When reverting back to 3.1.8, the issue seems to go away. The release notes indicate some changes to the thread-related APIs but I don't know how relevant those are.

I don't think this is necessarily a HDF5 problem, so I will be following up with the Emscripten folks at some point - but any thoughts would help before I go over there. I do have a workaround but its robustness is debatable.

**Comment by bmaranville** [comment]
Thanks for the heads-up!  I was about to ask for some code to reproduce the error but I see you've already provided a link.

When working on libhdf5 in pyodide, I ran across a weird error where libhdf5 1.12.x would fail to compile for Emscripten 2.0.27 but would compile in 2.0.26 and 2.0.28+.  Go figure.  In very limited testing, it seems like 1.13.1 compiles most of the time even when 1.12.x doesn't.  So... sometimes it's Emscripten? (or LLVM?)

**Comment by LTLA** [comment]
Yeah, it's pretty wild. For example, this particular bug also seems to depend on the availability of cores, which determines whether the timings will conflict or not. The availability of cores, in turn, depends on what else you're running on the machine at the same time. In my case, I suspect that the frequency of the segfaults varied with the complexity of the music I was playing on Youtube.

Fun times.

**Comment by LTLA** [comment]
This seems to have been fixed in later versions of Emscripten - fingers crossed.
